stages:
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cabal/store

cabal:
  stage: build
  image: haskell:8.6.5
  script:
    - cabal v2-update
    - cabal v2-install hpack
    - cabal v2-exec hpack
    - cabal v2-install --only-dependencies --enable-tests
    - cabal v2-configure --enable-tests
    - cabal v2-build
    - cabal v2-test
